# Generated by Django 3.1.11 on 2021-11-24 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=300, unique=True)),
                ('qr_code', models.CharField(max_length=450, unique=True)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(max_length=230)),
                ('receiver_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_email', to=settings.AUTH_USER_MODEL)),
                ('sender_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=400, null=True)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
        ),
    ]
