# Generated by Django 3.1.11 on 2021-11-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(default='sm9kqutvcdr2lcarrmv8', verbose_name='Invoice Slug'),
        ),
    ]
