# Generated by Django 3.1.11 on 2021-11-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(default='6nqtav51kaqrbrd9nhf1', verbose_name='Invoice Slug'),
        ),
    ]
