# Generated by Django 3.1.11 on 2021-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20211124_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(default='uqw7x6jci1lbj47dlxmr', verbose_name='Invoice Slug'),
        ),
    ]
