# Generated by Django 3.1.11 on 2021-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20211124_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(default='5vvnlrk4f4jl7gyefsyt', verbose_name='Invoice Slug'),
        ),
    ]
