# Generated by Django 3.1.11 on 2021-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20211129_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(verbose_name='Invoice Slug'),
        ),
    ]
