# Generated by Django 3.2.9 on 2021-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20211129_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='jvfa8cr0agk', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.CharField(default='zvjxisj8vd4a', max_length=450, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
