# Generated by Django 3.2.9 on 2021-12-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20211209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='trqg2wwylble', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.CharField(default='qlouu0oaibmc', max_length=450, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoices.invoice'),
        ),
    ]
