# Generated by Django 3.2.9 on 2021-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20211209_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='b0c5g8aqdylr', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.CharField(default='ymangga9foel', max_length=450, unique=True),
        ),
    ]
