# Generated by Django 3.1.11 on 2021-11-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='ieftuiz0k73jrzmjxzfg', verbose_name='User Slug'),
        ),
    ]
