# Generated by Django 3.1.11 on 2021-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211124_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='bsygyxxjkblgkmybfyen', verbose_name='User Slug'),
        ),
    ]
