# Generated by Django 3.1.11 on 2021-11-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211124_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Is Customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='px9j2sikfpypqyvvwvxm', verbose_name='User Slug'),
        ),
    ]
