# Generated by Django 3.1.11 on 2021-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211124_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='ef3n89wv42a3bnxoajdv', verbose_name='User Slug'),
        ),
    ]
