# Generated by Django 3.1.11 on 2021-11-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20211124_1255'),
        ('accounts', '0009_auto_20211124_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, max_length=550, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='ogy5t7ynf4rhzxtqe5hm', verbose_name='User Slug'),
        ),
    ]
