# Generated by Django 3.1.11 on 2021-11-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_abbreviation', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(default='dau23kzqrqz0akaricc3', verbose_name='Country Slug')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='eiidolgljix8ccqlrtis', verbose_name='State Slug')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(default='i0cvmpcux2msxkdytrmk', verbose_name='City Slug')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.state')),
            ],
        ),
    ]
