# Generated by Django 3.1.11 on 2021-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='oapp2p6x19bs6uvxp4vj', verbose_name='City Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='vezgcvl1bm5jxcm6youn', verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='qw46warlbdnomsoqgmcb', verbose_name='State Slug'),
        ),
    ]
