# Generated by Django 3.1.11 on 2021-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20211124_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='6yaplayq6xpkz05ahrti', verbose_name='City Slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='zoxuconfwm44t6rqxgqi', verbose_name='Country Slug'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='e1pm3nwj7p0bpe3trf0d', verbose_name='State Slug'),
        ),
    ]
