# Generated by Django 3.2.9 on 2021-12-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20211209_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='address.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='address.country'),
        ),
    ]
